#include "ps1_texture_pages.h"
#include "ps1_utils.h"
#include "stdio_compat.h"
#include "string_compat.h"
#include "utils.h"
#include <stdlib.h>

#define PS1_CLUT_Y4 496
#define PS1_CLUT_Y8 480
#define PS1_CLUT4_SLOTS 64
#define PS1_CLUT8_SLOTS 64
#define CLUT4_BYTES 64
#define CLUT8_BYTES 1024

static uint16_t rd16(FILE* f) { uint8_t b[2]; if(fread(b,1,2,f)!=2)return 0; return(uint16_t)(b[0]|((uint16_t)b[1]<<8)); }
static uint32_t rd32(FILE* f) { uint8_t b[4]; if(fread(b,1,4,f)!=4)return 0; return(uint32_t)b[0]|((uint32_t)b[1]<<8)|((uint32_t)b[2]<<16)|((uint32_t)b[3]<<24); }
static bool parseAtlas(Ps1TexturePages*c,FILE*f){uint8_t version;uint16_t tileCount;if(fread(&version,1,1,f)!=1||version!=0)return false;c->tpagCount=rd16(f);tileCount=rd16(f);c->atlasCount=rd16(f);if(!c->tpagCount||!c->atlasCount)return false;c->tpag=(Ps1PageTPAG*)safeMalloc((size_t)c->tpagCount*sizeof(*c->tpag));c->atlases=(Ps1PageAtlas*)safeMalloc((size_t)c->atlasCount*sizeof(*c->atlases));if(!c->tpag||!c->atlases)return false;for(uint16_t i=0;i<c->atlasCount;++i){Ps1PageAtlas*a=&c->atlases[i];a->dataOffset=rd32(f);a->width=rd16(f);a->height=rd16(f);if(fread(&a->bpp,1,1,f)!=1)return false;a->dataSize=rd32(f);if(fread(&a->compression,1,1,f)!=1)return false;if((a->bpp!=4&&a->bpp!=8)||!a->width||!a->height||a->width>1024||a->height>1024)return false;}for(uint16_t i=0;i<c->tpagCount;++i){Ps1PageTPAG*e=&c->tpag[i];e->atlasId=rd16(f);e->atlasX=rd16(f);e->atlasY=rd16(f);e->width=rd16(f);e->height=rd16(f);e->cropX=rd16(f);e->cropY=rd16(f);e->cropW=rd16(f);e->cropH=rd16(f);e->clutIndex=rd16(f);if(e->atlasId>=c->atlasCount)return false;}if(tileCount&&fseek(f,(long)tileCount*30L,SEEK_CUR)!=0)return false;return true;}
static uint16_t rgbaToPs1(uint8_t r,uint8_t g,uint8_t b,uint8_t a){if(a==0)return 0;uint16_t v=(uint16_t)((r>>3)|((g>>3)<<5)|((b>>3)<<10));if(a<255)v|=0x8000u;return v;}
static bool loadCluts(Ps1TexturePages*c,const char*name,uint8_t bpp){char*path=PS1Utils_createDevicePath(name);FILE*f=fopen(path,"rb");free(path);if(!f)return false;const uint32_t bytes=(bpp==4)?CLUT4_BYTES:CLUT8_BYTES;const uint32_t count=(bpp==4)?PS1_CLUT4_SLOTS:PS1_CLUT8_SLOTS;Ps1PageClut*slots=(bpp==4)?c->clut4:c->clut8;fseek(f,0,SEEK_END);long size=ftell(f);fseek(f,0,SEEK_SET);if(size<0||((uint32_t)size%bytes)!=0||(uint32_t)size/bytes>count){fclose(f);return false;}for(uint32_t i=0,n=(uint32_t)size/bytes;i<n;++i){uint8_t raw[CLUT8_BYTES];uint16_t colors[256];const uint32_t colorsN=(bpp==4)?16u:256u;if(fread(raw,1,bytes,f)!=bytes){fclose(f);return false;}for(uint32_t j=0;j<colorsN;++j){uint32_t o=j*4u;colors[j]=rgbaToPs1(raw[o],raw[o+1],raw[o+2],raw[o+3]);}RECT r;if(bpp==4){r.x=(int16_t)((i&63u)*16u);r.y=PS1_CLUT_Y4;r.w=16;r.h=1;}else{r.x=(int16_t)((i&3u)*256u);r.y=(int16_t)(PS1_CLUT_Y8+(i>>2));r.w=256;r.h=1;}DrawSync(0);LoadImage(&r,(uint32_t*)colors);DrawSync(0);slots[i].valid=true;slots[i].index=(uint16_t)i;slots[i].x=(uint16_t)r.x;slots[i].y=(uint16_t)r.y;slots[i].lastUsed=c->frameCounter;}fclose(f);return true;}
static uint32_t rowBytes(const Ps1PageAtlas*a){return a->bpp==4?((uint32_t)a->width+1u)/2u:(uint32_t)a->width;}static uint32_t pagePixelWidth(const Ps1PageAtlas*a){return a->bpp==4?256u:128u;}static uint32_t pageByteWidth(void){return 128u;}
static bool decodeRaw(FILE*f,const Ps1PageAtlas*a,uint16_t px,uint16_t py,uint8_t*out){const uint32_t rb=rowBytes(a),bw=pageByteWidth(),pageW=pagePixelWidth(a),sxPixels=(uint32_t)px*pageW,sx=sxPixels/(a->bpp==4?2u:1u),sy=(uint32_t)py*256u;memset(out,0,PS1_TEX_PAGE_BYTES);for(uint32_t y=0;y<256u;++y){uint32_t srcY=sy+y;if(srcY>=a->height||sx>=rb)continue;uint32_t n=rb-sx;if(n>bw)n=bw;if(fseek(f,(long)(a->dataOffset+srcY*rb+sx),SEEK_SET)!=0)return false;if(fread(out+y*bw,1,n,f)!=n)return false;}return true;}
static bool decodeRle(FILE*f,const Ps1PageAtlas*a,uint16_t px,uint16_t py,uint8_t*out){const uint32_t rb=rowBytes(a),bw=pageByteWidth(),pageW=pagePixelWidth(a),sx=(uint32_t)px*pageW,sy=(uint32_t)py*256u,sxByte=sx/(a->bpp==4?2u:1u),total=rb*(uint32_t)a->height;uint32_t src=0,dst=0;memset(out,0,PS1_TEX_PAGE_BYTES);while(src+2u<=a->dataSize&&dst<total){uint8_t run,value;if(fread(&run,1,1,f)!=1||fread(&value,1,1,f)!=1)return false;src+=2u;if(!run)continue;uint32_t end=dst+(uint32_t)run;if(end>total)end=total;uint32_t p=dst;while(p<end){uint32_t row=p/rb,rowEnd=(row+1u)*rb,target0=row*rb+sxByte,target1=target0+bw,q=p<target0?target0:p;if(q<end&&q<target1&&row>=sy&&row<sy+256u){uint32_t copyEnd=end<target1?end:target1,drow=row-sy,dcol=q-target0;for(uint32_t i=q;i<copyEnd;++i)out[drow*bw+dcol++]=value;}if(p<rowEnd)p=rowEnd;else p=end;}dst+=run;if(dst>total)dst=total;}return dst==total;}
static int findPage(Ps1TexturePages*c,uint16_t atlas,uint16_t px,uint16_t py,uint8_t bpp){for(int i=0;i<PS1_TEX_PAGE_SLOTS;++i){Ps1PageSlot*s=&c->pages[i];if(s->valid&&s->atlasId==atlas&&s->pageX==px&&s->pageY==py&&s->bpp==bpp)return i;}return-1;}
static int allocPage(Ps1TexturePages*c){int victim=-1;uint32_t oldest=0xffffffffu;for(int i=0;i<PS1_TEX_PAGE_SLOTS;++i){Ps1PageSlot*s=&c->pages[i];if(!s->valid)return i;if(s->lastUsed==c->frameCounter)continue;if(s->lastUsed<oldest){oldest=s->lastUsed;victim=i;}}return victim;}
static uint16_t makeClut(uint16_t x,uint16_t y){return getClut(x,y);}static uint16_t makeTPage(uint8_t bpp,uint16_t x,uint16_t y){return getTPage(bpp==4?0:1,0,x,y);}
static bool uploadPage(Ps1TexturePages*c,uint16_t atlas,uint16_t px,uint16_t py){if(atlas>=c->atlasCount)return false;const Ps1PageAtlas*a=&c->atlases[atlas];int slot=allocPage(c);if(slot<0)return false;if(!c->texturesFile){char*path=PS1Utils_createDevicePath("TEXTURES.BIN");c->texturesFile=fopen(path,"rb");free(path);}if(!c->texturesFile)return false;uint8_t*data=c->pageData;if(fseek(c->texturesFile,(long)a->dataOffset,SEEK_SET)!=0)return false;bool ok=a->compression==1?decodeRle(c->texturesFile,a,px,py,data):decodeRaw(c->texturesFile,a,px,py,data);if(!ok)return false;RECT r;r.x=(int16_t)(PS1_TEX_PAGE_VRAM_X+slot*PS1_TEX_PAGE_WORDS);r.y=PS1_TEX_PAGE_VRAM_Y;r.w=PS1_TEX_PAGE_WORDS;r.h=PS1_TEX_PAGE_HEIGHT;DrawSync(0);LoadImage(&r,(uint32_t*)data);DrawSync(0);c->pages[slot].valid=true;c->pages[slot].atlasId=atlas;c->pages[slot].pageX=px;c->pages[slot].pageY=py;c->pages[slot].bpp=a->bpp;c->pages[slot].vramX=(uint16_t)r.x;c->pages[slot].vramY=(uint16_t)r.y;c->pages[slot].lastUsed=c->frameCounter;return true;}
static int ensurePage(Ps1TexturePages*c,uint16_t atlas,uint16_t px,uint16_t py){if(atlas>=c->atlasCount)return-1;uint8_t bpp=c->atlases[atlas].bpp;int i=findPage(c,atlas,px,py,bpp);if(i>=0){c->pages[i].lastUsed=c->frameCounter;return i;}if(!uploadPage(c,atlas,px,py))return-1;return findPage(c,atlas,px,py,bpp);}static uint16_t resolveClut(Ps1TexturePages*c,uint8_t bpp,uint16_t index){Ps1PageClut*s=bpp==4?c->clut4:c->clut8;if(index>=64u||!s[index].valid)return 0;s[index].lastUsed=c->frameCounter;return makeClut(s[index].x,s[index].y);}
bool Ps1TexturePages_init(Ps1TexturePages*c){if(!c)return false;memset(c,0,sizeof(*c));c->frameCounter=1;char*path=PS1Utils_createDevicePath("ATLAS.BIN");FILE*f=fopen(path,"rb");free(path);if(!f)return false;bool ok=parseAtlas(c,f);fclose(f);if(!ok||!loadCluts(c,"CLUT4.BIN",4)||!loadCluts(c,"CLUT8.BIN",8)){Ps1TexturePages_shutdown(c);return false;}return true;}void Ps1TexturePages_shutdown(Ps1TexturePages*c){if(!c)return;if(c->texturesFile)fclose(c->texturesFile);c->texturesFile=NULL;free(c->tpag);free(c->atlases);c->tpag=NULL;c->atlases=NULL;c->tpagCount=c->atlasCount=0;}void Ps1TexturePages_beginFrame(Ps1TexturePages*c){if(c)++c->frameCounter;}
uint16_t Ps1TexturePages_resolveTPAG(Ps1TexturePages*c,int32_t index,Ps1TexturePagePiece out[PS1_TEX_MAX_TPAG_PIECES]){if(!c||!out||index<0||(uint32_t)index>=c->tpagCount)return 0;const Ps1PageTPAG*e=&c->tpag[index];const Ps1PageAtlas*a=&c->atlases[e->atlasId];const uint32_t pw=pagePixelWidth(a),ph=256u;uint16_t count=0;uint32_t endX=(uint32_t)e->atlasX+e->width,endY=(uint32_t)e->atlasY+e->height;for(uint32_t py=e->atlasY/ph;py*ph<endY;++py){for(uint32_t px=e->atlasX/pw;px*pw<endX;++px){if(count>=PS1_TEX_MAX_TPAG_PIECES)return 0;int slot=ensurePage(c,e->atlasId,(uint16_t)px,(uint16_t)py);if(slot<0)return 0;uint32_t ix0=e->atlasX>px*pw?e->atlasX:px*pw,iy0=e->atlasY>py*ph?e->atlasY:py*ph,ix1=endX<(px+1u)*pw?endX:(px+1u)*pw,iy1=endY<(py+1u)*ph?endY:(py+1u)*ph;Ps1TexturePagePiece*q=&out[count++];q->x=(int16_t)(e->cropX+((ix0-e->atlasX)*(uint32_t)e->cropW)/e->width);q->y=(int16_t)(e->cropY+((iy0-e->atlasY)*(uint32_t)e->cropH)/e->height);int32_t sx1=(int32_t)e->cropX+((ix1-e->atlasX)*(uint32_t)e->cropW)/e->width;int32_t sy1=(int32_t)e->cropY+((iy1-e->atlasY)*(uint32_t)e->cropH)/e->height;q->width=(uint16_t)(sx1-q->x);q->height=(uint16_t)(sy1-q->y);q->u=(uint16_t)(ix0-px*pw);q->v=(uint16_t)(iy0-py*ph);q->tpage=makeTPage(a->bpp,c->pages[slot].vramX,c->pages[slot].vramY);q->clut=resolveClut(c,a->bpp,e->clutIndex);q->cropX=e->cropX;q->cropY=e->cropY;q->cropW=e->cropW;q->cropH=e->cropH;q->atlasWidth=e->width;q->atlasHeight=e->height;if(!q->clut)return 0;}}return count;}
