#include "stdio_compat.h"
#include "string_compat.h"
#include <unistd.h>
#include 
#include <psxcd.h>
#include "../utils.h"
#include "ps1_utils.h"

PS1DeviceKey deviceKey;
bool deviceKeyLoaded = false;

void PS1Utils_extractDeviceKey(const char* path) {
    require(!deviceKeyLoaded);

    char* pos = strchr(path, ':');
    requireNotNull(pos);

    size_t length = pos - path;
    char* result = (char *)safeMalloc((length + 1) * sizeof(char));
    strncpy(result, path, length);
    result[length] = '\0';

    // The "result" is the device key as a string (example: "mass" or "host")
    deviceKey.key = result;
    deviceKey.usesISO9660 = strncmp(result, "cdrom", strlen("cdrom")) == 0;

    deviceKeyLoaded = true;
}

// Loads the required IOP drivers based on the current device key
// For cdrom devices, this loads the CDVD filesystem modules so we can read from the disc
void PS1Utils_loadFSDrivers() {
    require(deviceKeyLoaded);

    if (deviceKey.usesISO9660) {
        logInfo("PS1Utils: Loading CDVD drivers for device key '%s'\n", deviceKey.key);

        int ret;
        ret = SifLoadModule("rom0:CDVDMAN", 0, nullptr);
        if (0 > ret) {
            logError("PS1Utils: Failed to load CDVDMAN: %d\n", ret);
            abort();
        }

        ret = SifLoadModule("rom0:CDVDFSV", 0, nullptr);
        if (0 > ret) {
            logError("PS1Utils: Failed to load CDVDFSV: %d\n", ret);
            abort();
        }

        sceCdInit(SCECdINIT);
        logInfo("PS1Utils: CDVD initialized\n");
    }
}

#ifdef GPROF_PROFILING
// Embedded USB mass storage IRX modules (generated by bin2c at build time, only in profiler builds)
extern unsigned char usbd_irx[];
extern unsigned int size_usbd_irx;
extern unsigned char bdm_irx[];
extern unsigned int size_bdm_irx;
extern unsigned char bdmfs_fatfs_irx[];
extern unsigned int size_bdmfs_fatfs_irx;
extern unsigned char usbmass_bd_irx[];
extern unsigned int size_usbmass_bd_irx;

void PS1Utils_loadMassStorageDrivers() {
    require(deviceKeyLoaded);

    logInfo("PS1Utils: Loading USB mass storage drivers for gprof output...\n");

    int ret;
    ret = SifExecModuleBuffer(usbd_irx, size_usbd_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        logWarn("PS1Utils: Failed to load usbd: %d\n", ret);
    }

    ret = SifExecModuleBuffer(bdm_irx, size_bdm_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        logWarn("PS1Utils: Failed to load bdm: %d\n", ret);
    }

    ret = SifExecModuleBuffer(bdmfs_fatfs_irx, size_bdmfs_fatfs_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        logWarn("PS1Utils: Failed to load bdmfs_fatfs: %d\n", ret);
    }

    ret = SifExecModuleBuffer(usbmass_bd_irx, size_usbmass_bd_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        logWarn("PS1Utils: Failed to load usbmass_bd: %d\n", ret);
    }

    // Wait for USB device detection
    sleep(3);

    logInfo("PS1Utils: USB mass storage drivers loaded\n");
}
#endif

// Creates a path with the device key + path for the loaded device key
// You need to free after using the path!
char* PS1Utils_createDevicePath(const char* path) {
    require(deviceKeyLoaded);

    if (deviceKey.usesISO9660) {
        size_t len = strlen(deviceKey.key) + 3 + strlen(path) + 2 + 1;
        char* devicePath = (char *)safeMalloc(len);
        snprintf(devicePath, len, "%s:\\%s;1", deviceKey.key, path);
        return devicePath;
    } else {
        size_t len = strlen(deviceKey.key) + 1 + strlen(path) + 1;
        char* devicePath = (char *)safeMalloc(len);
        snprintf(devicePath, len, "%s:%s", deviceKey.key, path);
        return devicePath;
    }
}
