#include "ps1_renderer.h"
#include "runner.h"
#include "utils.h"
#include "log.h"
#include "ps1_texture_pages.h"
#include "ps1_sprite_mapping.h"
#include "ps1_atlas_tiles.h"
#include <psxgpu.h>
#include <psxetc.h>
#include <string.h>
#include <math.h>

#define PS1_WIDTH 320
#define PS1_HEIGHT 240
#define PS1_OT_LENGTH 32
#define PS1_PACKET_BYTES 32768
#define PS1_Z 8

typedef struct { DISPENV disp; DRAWENV draw; uint32_t ot[PS1_OT_LENGTH]; uint8_t packet[PS1_PACKET_BYTES]; } Ps1RenderBuffer;
typedef struct { Renderer base; Ps1RenderBuffer buffers[2]; uint8_t* nextPacket; int active; float scaleX,scaleY,offsetX,offsetY; int32_t viewX,viewY; int32_t blendMode; BlendFactors blendFactors; bool blendEnable,alphaTestEnable; uint8_t alphaTestRef; bool colorWriteR,colorWriteG,colorWriteB,colorWriteA; Ps1TexturePages textures; bool texturesReady; } Ps1Renderer;
static Ps1Renderer* gPs1Renderer=NULL;
static bool gAtlasTilesReady=false;
static void* allocPrim(Ps1Renderer*p,size_t n){Ps1RenderBuffer*b=&p->buffers[p->active];if((size_t)(p->nextPacket-b->packet)+n>PS1_PACKET_BYTES)return NULL;void*q=p->nextPacket;p->nextPacket+=n;return q;}
static void queuePrim(Ps1Renderer*p,void*q){addPrim(&p->buffers[p->active].ot[PS1_Z],q);}
static uint8_t cr(uint32_t c){return c&255;} static uint8_t cg(uint32_t c){return(c>>8)&255;} static uint8_t cb(uint32_t c){return(c>>16)&255;}
static int sx(Ps1Renderer*p,float x){return(int)((x-p->viewX)*p->scaleX+p->offsetX);} static int sy(Ps1Renderer*p,float y){return(int)((y-p->viewY)*p->scaleY+p->offsetY);}
static void ps1Init(Renderer*r,DataWin*d){Ps1Renderer*p=(Ps1Renderer*)r;ResetGraph(0);SetDefDispEnv(&p->buffers[0].disp,0,0,PS1_WIDTH,PS1_HEIGHT);SetDefDispEnv(&p->buffers[1].disp,0,PS1_HEIGHT,PS1_WIDTH,PS1_HEIGHT);SetDefDrawEnv(&p->buffers[0].draw,0,PS1_HEIGHT,PS1_WIDTH,PS1_HEIGHT);SetDefDrawEnv(&p->buffers[1].draw,0,0,PS1_WIDTH,PS1_HEIGHT);p->buffers[0].draw.isbg=1;p->buffers[1].draw.isbg=1;setRGB0(&p->buffers[0].draw,0,0,0);setRGB0(&p->buffers[1].draw,0,0,0);PutDispEnv(&p->buffers[0].disp);PutDrawEnv(&p->buffers[0].draw);SetDispMask(1);r->dataWin=d;r->drawColor=0xFFFFFF;r->drawAlpha=1;r->drawFont=-1;r->drawHalign=0;r->drawValign=0;r->circlePrecision=24;p->scaleX=p->scaleY=1;p->blendEnable=true;p->colorWriteR=p->colorWriteG=p->colorWriteB=p->colorWriteA=true;p->blendMode=bm_normal;p->texturesReady=Ps1TexturePages_init(&p->textures);if(!p->texturesReady)logWarn("Ps1Renderer: page texture cache unavailable; sprite calls will be skipped\n");if(Ps1AtlasTiles_init()){gAtlasTilesReady=true;}else{logWarn("Ps1Renderer: ATLAS.BIN tile table unavailable; RoomTile will use TPAG fallback\n");}FntLoad(320,256);}
static void ps1Destroy(Renderer*r){Ps1Renderer*p=(Ps1Renderer*)r;if(p->texturesReady)Ps1TexturePages_shutdown(&p->textures);if(gAtlasTilesReady){Ps1AtlasTiles_shutdown();gAtlasTilesReady=false;}if(gPs1Renderer==p)gPs1Renderer=NULL;free(p);}
static void ps1BeginFrame(Renderer*r,int32_t gw,int32_t gh,int32_t ww,int32_t wh){Ps1Renderer*p=(Ps1Renderer*)r;(void)ww;(void)wh;p->scaleX=gw>0?(float)PS1_WIDTH/gw:1;p->scaleY=gh>0?(float)PS1_HEIGHT/gh:1;if(p->scaleY<p->scaleX)p->scaleX=p->scaleY;p->scaleY=p->scaleX;p->offsetX=(PS1_WIDTH-gw*p->scaleX)*.5f;p->offsetY=(PS1_HEIGHT-gh*p->scaleY)*.5f;ClearOTagR(p->buffers[p->active].ot,PS1_OT_LENGTH);p->nextPacket=p->buffers[p->active].packet;if(p->texturesReady)Ps1TexturePages_beginFrame(&p->textures);}
static void ps1EndFrameInit(Renderer*r){(void)r;} static void ps1EndFrameEnd(Renderer*r){(void)r;}
static void ps1BeginView(Renderer*r,int32_t vx,int32_t vy,int32_t vw,int32_t vh,int32_t px,int32_t py,int32_t pw,int32_t ph,float a){Ps1Renderer*p=(Ps1Renderer*)r;(void)a;p->viewX=vx;p->viewY=vy;float sxv=pw>0?(float)pw/vw:1.0f,syv=ph>0?(float)ph/vh:1.0f,s=sxv<syv?sxv:syv;if(vw<=0||vh<=0)s=1.0f;p->scaleX=p->scaleY=s;p->offsetX=(float)px+(pw-vw*s)*.5f;p->offsetY=(float)py+(ph-vh*s)*.5f;}
static void ps1EndView(Renderer*r){(void)r} static void ps1ApplyProjection(Renderer*r,const Matrix4f*a,const Matrix4f*b){(void)r;(void)a;(void)b;}
static void ps1BeginGUI(Renderer*r,int32_t gw,int32_t gh,int32_t px,int32_t py,int32_t pw,int32_t ph,int32_t t){Ps1Renderer*p=(Ps1Renderer*)r;(void)t;p->viewX=p->viewY=0;if(pw<=0)pw=PS1_WIDTH;if(ph<=0)ph=PS1_HEIGHT;p->scaleX=gw>0?(float)pw/gw:1;p->scaleY=gh>0?(float)ph/gh:1;if(p->scaleY<p->scaleX)p->scaleX=p->scaleY;p->scaleY=p->scaleX;p->offsetX=(float)px+(pw-gw*p->scaleX)*.5f;p->offsetY=(float)py+(ph-gh*p->scaleY)*.5f;}
static void ps1SetGuiProjection(Renderer*r,int32_t gw,int32_t gh,int32_t pw,int32_t ph,bool s){(void)s;ps1BeginGUI(r,gw,gh,0,0,pw,ph,APPLICATION_SURFACE_ID);} static void ps1EndGUI(Renderer*r){(void)r;}
static void ps1DrawRectangle(Renderer*r,float x1,float y1,float x2,float y2,uint32_t c,float a,bool o){Ps1Renderer*p=(Ps1Renderer*)r;int ax=sx(p,x1),ay=sy(p,y1),bx=sx(p,x2),by=sy(p,y2);if(o){TILE*t=(TILE*)allocPrim(p,sizeof(TILE));if(t){setTile(t);setXY0(t,ax,ay);setWH(t,bx-ax,1);setRGB0(t,cr(c),cg(c),cb(c));queuePrim(p,t);}t=(TILE*)allocPrim(p,sizeof(TILE));if(t){setTile(t);setXY0(t,ax,by-1);setWH(t,bx-ax,1);setRGB0(t,cr(c),cg(c),cb(c));queuePrim(p,t);}t=(TILE*)allocPrim(p,sizeof(TILE));if(t){setTile(t);setXY0(t,ax,ay);setWH(t,1,by-ay);setRGB0(t,cr(c),cg(c),cb(c));queuePrim(p,t);}t=(TILE*)allocPrim(p,sizeof(TILE));if(t){setTile(t);setXY0(t,bx-1,ay);setWH(t,1,by-ay);setRGB0(t,cr(c),cg(c),cb(c));queuePrim(p,t);}}else{TILE*t=(TILE*)allocPrim(p,sizeof(TILE));if(!t)return;setTile(t);setXY0(t,ax,ay);setWH(t,bx-ax,by-ay);setRGB0(t,cr(c),cg(c),cb(c));if(a<1)setSemiTrans(t,1);queuePrim(p,t);}}
static void ps1DrawRectangleColor(Renderer*r,float x1,float y1,float x2,float y2,uint32_t c1,uint32_t c2,uint32_t c3,uint32_t c4,float a,bool o){(void)c2;(void)c3;(void)c4;ps1DrawRectangle(r,x1,y1,x2,y2,c1,a,o);}
static void ps1DrawLine(Renderer*r,float x1,float y1,float x2,float y2,float w,uint32_t c,float a){Ps1Renderer*p=(Ps1Renderer*)r;LINE_F2*l=(LINE_F2*)allocPrim(p,sizeof(LINE_F2));if(!l)return;setLineF2(l);setXY2(l,sx(p,x1),sy(p,y1),sx(p,x2),sy(p,y2));setRGB0(l,cr(c),cg(c),cb(c));if(a<1)setSemiTrans(l,1);queuePrim(p,l);(void)w;}
static void ps1DrawLineColor(Renderer*r,float x1,float y1,float x2,float y2,float w,uint32_t c1,uint32_t c2,float a){(void)c2;ps1DrawLine(r,x1,y1,x2,y2,w,c1,a);}
static void ps1DrawTriangle(Renderer*r,float x1,float y1,float x2,float y2,float x3,float y3,uint32_t c1,uint32_t c2,uint32_t c3,float a,bool o){(void)c2;(void)c3;(void)o;Ps1Renderer*p=(Ps1Renderer*)r;POLY_F3*q=(POLY_F3*)allocPrim(p,sizeof(POLY_F3));if(!q)return;setPolyF3(q);setXY3(q,sx(p,x1),sy(p,y1),sx(p,x2),sy(p,y2),sx(p,x3),sy(p,y3));setRGB0(q,cr(c1),cg(c1),cb(c1));if(a<1)setSemiTrans(q,1);queuePrim(p,q);}
static void rotatePoint(float cx,float cy,float x,float y,float rad,float*ox,float*oy){float dx=x-cx,dy=y-cy,s=sinf(rad),c=cosf(rad);*ox=cx+dx*c-dy*s;*oy=cy+dx*s+dy*c;}
static uint16_t resolvePieces(Ps1Renderer*p,int32_t t,Ps1TexturePagePiece out[PS1_TEX_MAX_TPAG_PIECES]){if(!p->texturesReady)return 0;return Ps1TexturePages_resolveTPAG(&p->textures,t,out);}
static void emitSpritePiece(Ps1Renderer*p,const Ps1TexturePagePiece*pc,const Ps1SpriteMappedRect*m,float x,float y,float xs,float ys,float ang,float px,float py,uint32_t c,float a){float x0=x-px*xs+m->srcX*xs,y0=y-py*ys+m->srcY*ys,x1=x0+m->srcW*xs,y1=y0+m->srcH*ys,ax,ay,bx,by,cx,cy,dx,dy,rad=ang*0.017453292519943295f;rotatePoint(x,y,x0,y0,rad,&ax,&ay);rotatePoint(x,y,x1,y0,rad,&bx,&by);rotatePoint(x,y,x1,y1,rad,&cx,&cy);rotatePoint(x,y,x0,y1,rad,&dx,&dy);POLY_FT4*q=(POLY_FT4*)allocPrim(p,sizeof(POLY_FT4));if(!q)return;setPolyFT4(q);setXY4(q,sx(p,ax),sy(p,ay),sx(p,bx),sy(p,by),sx(p,cx),sy(p,cy),sx(p,dx),sy(p,dy));setUV4(q,(uint8_t)(pc->u+m->atlasX),(uint8_t)(pc->v+m->atlasY),(uint8_t)(pc->u+m->atlasX+m->atlasW),(uint8_t)(pc->v+m->atlasY),(uint8_t)(pc->u+m->atlasX+m->atlasW),(uint8_t)(pc->v+m->atlasY+m->atlasH),(uint8_t)(pc->u+m->atlasX),(uint8_t)(pc->v+m->atlasY+m->atlasH));setClut(q,pc->clut);setTPage(q,pc->tpage);setRGB0(q,cr(c),cg(c),cb(c));if(a<1)setSemiTrans(q,1);queuePrim(p,q);}
static void ps1DrawSpritePart(Renderer*r,int32_t t,int32_t sx0,int32_t sy0,int32_t sw,int32_t sh,float x,float y,float xs,float ys,float ang,float px,float py,uint32_t c,float a){Ps1Renderer*p=(Ps1Renderer*)r;Ps1TexturePagePiece pcs[PS1_TEX_MAX_TPAG_PIECES];uint16_t n=resolvePieces(p,t,pcs);if(!n||sw<=0||sh<=0)return;for(uint16_t i=0;i<n;i++){Ps1SpriteMappedRect m;if(Ps1SpriteMap_piece(&pcs[i],sx0,sy0,sw,sh,&m))emitSpritePiece(p,&pcs[i],&m,x,y,xs,ys,ang,px,py,c,a);}}
static void ps1DrawSprite(Renderer*r,int32_t t,float x,float y,float ox,float oy,float xs,float ys,float ang,uint32_t c,float a){Ps1TexturePagePiece pcs[PS1_TEX_MAX_TPAG_PIECES];uint16_t n=resolvePieces((Ps1Renderer*)r,t,pcs);if(!n)return;int w=0,h=0;for(uint16_t i=0;i<n;i++){int e=(int)pcs[i].cropX+(int)pcs[i].cropW;if(e>w)w=e;e=(int)pcs[i].cropY+(int)pcs[i].cropH;if(e>h)h=e;}if(w<=0||h<=0)return;ps1DrawSpritePart(r,t,0,0,w,h,x,y,xs,ys,ang,ox,oy,c,a);}
static void ps1DrawSpritePartColor(Renderer*r,int32_t t,int32_t x0,int32_t y0,int32_t w,int32_t h,float x,float y,float xs,float ys,float ang,float px,float py,uint32_t c1,uint32_t c2,uint32_t c3,uint32_t c4,float a){(void)c2;(void)c3;(void)c4;ps1DrawSpritePart(r,t,x0,y0,w,h,x,y,xs,ys,ang,px,py,c1,a);}
static void ps1DrawSpritePos(Renderer*r,int32_t t,float x1,float y1,float x2,float y2,float x3,float y3,float x4,float y4,float a){Ps1Renderer*p=(Ps1Renderer*)r;Ps1TexturePagePiece pcs[PS1_TEX_MAX_TPAG_PIECES];uint16_t n=resolvePieces(p,t,pcs);if(!n)return;int tw=0,th=0;for(uint16_t i=0;i<n;i++){int e=(int)pcs[i].cropX+(int)pcs[i].cropW;if(e>tw)tw=e;e=(int)pcs[i].cropY+(int)pcs[i].cropH;if(e>th)th=e;}if(tw<=0||th<=0)return;for(uint16_t i=0;i<n;i++){const Ps1TexturePagePiece*pc=&pcs[i];Ps1SpriteMappedRect m;if(!Ps1SpriteMap_piece(pc,0,0,tw,th,&m))continue;float u0=(float)m.srcX/tw,v0=(float)m.srcY/th,u1=(float)(m.srcX+m.srcW)/tw,v1=(float)(m.srcY+m.srcH)/th;float ax=x1+(x2-x1)*u0+(x4-x1)*v0,ay=y1+(y2-y1)*u0+(y4-y1)*v0,bx=x1+(x2-x1)*u1+(x4-x1)*v0,by=y1+(y2-y1)*u1+(y4-y1)*v0,cx=x1+(x2-x1)*u1+(x4-x1)*v1,cy=y1+(y2-y1)*u1+(y4-y1)*v1,dx=x1+(x2-x1)*u0+(x4-x1)*v1,dy=y1+(y2-y1)*u0+(y4-y1)*v1;POLY_FT4*q=(POLY_FT4*)allocPrim(p,sizeof(POLY_FT4));if(!q)continue;setPolyFT4(q);setXY4(q,sx(p,ax),sy(p,ay),sx(p,bx),sy(p,by),sx(p,cx),sy(p,cy),sx(p,dx),sy(p,dy));setUV4(q,(uint8_t)(pc->u+m.atlasX),(uint8_t)(pc->v+m.atlasY),(uint8_t)(pc->u+m.atlasX+m.atlasW),(uint8_t)(pc->v+m.atlasY),(uint8_t)(pc->u+m.atlasX+m.atlasW),(uint8_t)(pc->v+m.atlasY+m.atlasH),(uint8_t)(pc->u+m.atlasX),(uint8_t)(pc->v+m.atlasY+m.atlasH));setClut(q,pc->clut);setTPage(q,pc->tpage);setRGB0(q,255,255,255);if(a<1)setSemiTrans(q,1);queuePrim(p,q);}}
static void ps1DrawTile(Renderer*r,RoomTile*t,float ox,float oy){Ps1Renderer*p=(Ps1Renderer*)r;if(!p||!t||!p->texturesReady)return;int32_t srcX=t->sourceX,srcY=t->sourceY,srcW=(int32_t)t->width,srcH=(int32_t)t->height;if(srcW<=0||srcH<=0||t->scaleX==0.0f||t->scaleY==0.0f)return;const Ps1AtlasTileEntry*entry=NULL;if(gAtlasTilesReady)entry=Ps1AtlasTiles_find(t->backgroundDefinition,srcX,srcY,srcW,srcH);float drawX=(float)t->x+ox,drawY=(float)t->y+oy;if(entry){Ps1TexturePagePiece pcs[PS1_TEX_MAX_TPAG_PIECES];uint16_t n=Ps1TexturePages_resolveAtlasTile(&p->textures,entry,pcs);for(uint16_t i=0;i<n;i++){Ps1SpriteMappedRect m;if(Ps1SpriteMap_piece(&pcs[i],srcX,srcY,srcW,srcH,&m))emitSpritePiece(p,&pcs[i],&m,drawX-srcX*t->scaleX,drawY-srcY*t->scaleY,t->scaleX,t->scaleY,0.0f,0.0f,0.0f,t->color,t->alpha);}}else{int32_t tpag=Renderer_resolveObjectTPAGIndex(p->base.dataWin,t);if(tpag>=0)ps1DrawSpritePart(r,tpag,srcX,srcY,srcW,srcH,drawX,drawY,t->scaleX,t->scaleY,0.0f,srcX,srcY,t->color,t->alpha);}}
static void ps1DrawSpriteTiled(Renderer*r,int32_t t,float ox,float oy,float x,float y,float xs,float ys,bool tx,bool ty,float rw,float rh,uint32_t c,float a){(void)tx;(void)ty;(void)rw;(void)rh;ps1DrawSprite(r,t,x,y,ox,oy,xs,ys,0,c,a);} static void ps1DrawTiledPart(Renderer*r,int32_t t,int32_t x,int32_t y,int32_t w,int32_t h,float dx,float dy,float dw,float dh,uint32_t c,float a){if(w>0&&h>0)ps1DrawSpritePart(r,t,x,y,w,h,dx,dy,dw/(float)w,dh/(float)h,0,0,0,c,a);}
static void ps1DrawText(Renderer*r,const char*t,float x,float y,float xs,float ys,float ang,float sep){(void)xs;(void)ys;(void)ang;(void)sep;Ps1Renderer*p=(Ps1Renderer*)r;p->nextPacket=(uint8_t*)FntSort(&p->buffers[p->active].ot[0],p->nextPacket,sx(p,x),sy(p,y),t);} static void ps1DrawTextColor(Renderer*r,const char*t,float x,float y,float xs,float ys,float ang,int32_t c1,int32_t c2,int32_t c3,int32_t c4,float a,float sep){(void)c2;(void)c3;(void)c4;(void)a;ps1DrawText(r,t,x,y,xs,ys,ang,sep);} static void ps1DrawSetBlendMode(Renderer*r,int32_t m){((Ps1Renderer*)r)->blendMode=m;} static void ps1DrawSetAlphaTest(Renderer*r,bool e,uint8_t ref){Ps1Renderer*p=(Ps1Renderer*)r;p->alphaTestEnable=e;p->alphaTestRef=ref;} static void ps1DrawSetColorWriteMask(Renderer*r,bool r0,bool g,bool b,bool aa){Ps1Renderer*p=(Ps1Renderer*)r;p->colorWriteR=r0;p->colorWriteG=g;p->colorWriteB=b;p->colorWriteA=aa;} static void ps1DrawSetBlendEnable(Renderer*r,bool e){((Ps1Renderer*)r)->blendEnable=e;} static void ps1DrawSetBlendFactors(Renderer*r,BlendFactors f){((Ps1Renderer*)r)->blendFactors=f;}
static void ps1Present(Renderer*r){Ps1Renderer*p=(Ps1Renderer*)r;DrawSync(0);VSync(0);PutDispEnv(&p->buffers[p->active].disp);PutDrawEnv(&p->buffers[p->active].draw);DrawOTagEnv(p->buffers[p->active].ot,&p->buffers[p->active].draw);p->active^=1;}
Renderer* Ps1Renderer_create(void){Ps1Renderer*p=(Ps1Renderer*)calloc(1,sizeof(*p));if(!p)return NULL;p->active=0;p->base.vtable=&(RendererVTable){.init=ps1Init,.destroy=ps1Destroy,.beginFrame=ps1BeginFrame,.endFrameInit=ps1EndFrameInit,.endFrameEnd=ps1EndFrameEnd,.beginView=ps1BeginView,.endView=ps1EndView,.applyProjection=ps1ApplyProjection,.beginGUI=ps1BeginGUI,.setGuiProjection=ps1SetGuiProjection,.endGUI=ps1EndGUI,.drawRectangle=ps1DrawRectangle,.drawRectangleColor=ps1DrawRectangleColor,.drawLine=ps1DrawLine,.drawLineColor=ps1DrawLineColor,.drawTriangle=ps1DrawTriangle,.drawSprite=ps1DrawSprite,.drawSpritePart=ps1DrawSpritePart,.drawSpritePartColor=ps1DrawSpritePartColor,.drawSpritePos=ps1DrawSpritePos,.drawSpriteTiled=ps1DrawSpriteTiled,.drawTile=ps1DrawTile,.drawTiledPart=ps1DrawTiledPart,.drawText=ps1DrawText,.drawTextColor=ps1DrawTextColor,.drawSetBlendMode=ps1DrawSetBlendMode,.drawSetAlphaTest=ps1DrawSetAlphaTest,.drawSetColorWriteMask=ps1DrawSetColorWriteMask,.drawSetBlendEnable=ps1DrawSetBlendEnable,.drawSetBlendFactors=ps1DrawSetBlendFactors,.present=ps1Present};gPs1Renderer=p;return &p->base;}
void Ps1Renderer_present(void){if(gPs1Renderer)ps1Present(&gPs1Renderer->base);}
